version: '3'
services:
  api:
    image: signaling:latest
    restart: always
    environment:
      - VIRTUAL_HOST=api.domain.com
      - LETSENCRYPT_HOST=api.domain.com
      - LETSENCRYPT_EMAIL=admin@domain.com

  ui:
    image: webrtcui:latest
    restart: always
    volumes:
      - ./config/ui.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - VIRTUAL_HOST=webrtc.domain.com
      - LETSENCRYPT_HOST=webrtc.domain.com
      - LETSENCRYPT_EMAIL=admin@domain.com
      - VITE_RTC_HOST=domain.com
      - VITE_STUN_SERVER=stun.domain.com
      - VITE_TURN_SERVER=turn.domain.com
      - VITE_TURN_USERNAME=username
      - VITE_TURN_PASSWORD=password
